### ISSUE TITLE
QA_Introduction_Prerequisite S/W_Broken-links 

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/analog-cmos-vlsi-circuit-design-iiith#1]
Defect Description :
In the Prerequisite S/W page section of the Introduction section of this lab, the link is navigating to error page.

Actual Result :
In the Prerequisite S/W page section of the Introduction section of this lab, the link is navigating to error page.

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers:Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

Attachments:
![qa_oe_avlsi_i01](https://cloud.githubusercontent.com/assets/13479177/26624825/bd0998d0-460f-11e7-98db-f6deb0ec9085.png)

**Comment by sravanthimodepu** [comment]
Updated the correct link to view the pre-requisites to run the simulation. Hence the issue is fixed.

**Comment by BSravanthi** [comment]
Issue is not yet fixed. Hence the issue is still opened.

**Comment by BSravanthi** [comment]
Closed #1

**Comment by sravanthimodepu** [comment]
Assigned the proper link and the Issue is fixed.
