### ISSUE TITLE
QA_Design and characterization of differential amplifier : Frequency Response (Vin v/s Frequency)_unwanted-sub-sections

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/analog-cmos-vlsi-circuit-design-iiith#29]
Defect Description :
In the menu of the Design and characterization of differential amplifier : Frequency Response (Vin v/s Frequency) experiment of this lab, found unwanted sub-sections.

Actual Result :
In the menu of the Design and characterization of differential amplifier : Frequency Response (Vin v/s Frequency) experiment of this lab, found unwanted empty sub-sections.

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers:Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

Attachments:
![qa_oe_avlsi_i26](https://cloud.githubusercontent.com/assets/13479177/26664441/564e1878-46af-11e7-8a3f-37c74c1fb4bd.png)

**Comment by sravanthimodepu** [comment]
Removed the unwanted section from the experiment. Hence the issue is resolved.

**Comment by BSravanthi** [comment]
Closed #29
