### ISSUE TITLE
QA_Design and characterization of common source amplifier with Resistive load : Transfer Characteristics (Vin v/s Vout)_Procedure_improper-alignment

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/analog-cmos-vlsi-circuit-design-iiith#3]
Defect Description :
In the Procedure page of "Design and characterization of common source amplifier with Resistive load : Transfer Characteristics (Vin v/s Vout)" experiment of this lab, the alignment for the second point is improper.

Actual Result :
In the Procedure page of "Design and characterization of common source amplifier with Resistive load : Transfer Characteristics (Vin v/s Vout)" experiment of this lab, the alignment for the second point is improper.

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers:Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

Attachments:
![qa_oe_avlsi_i03](https://cloud.githubusercontent.com/assets/13479177/26625470/d3e360ac-4611-11e7-8882-51821f305409.png)

**Comment by sravanthimodepu** [comment]
Aligned the steps properly. Hence the issue is fixed.

**Comment by BSravanthi** [comment]
Closed #3
