### ISSUE TITLE
QA_Design and characterization of differential to single-ended circuit : Transfer Characteristics (Vin v/s Vout)_Procedure_improper-alignment

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/analog-cmos-vlsi-circuit-design-iiith#34]
Defect Description :
In the Procedure page of "Design and characterization of differential to single-ended circuit : Transfer Characteristics (Vin v/s Vout)" experiment of this lab, the alignment for the second point is improper.

Actual Result :
In the Procedure page of "Design and characterization of differential to single-ended circuit : Transfer Characteristics (Vin v/s Vout)" experiment of this lab, the alignment for the second point is improper.

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers:Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

Attachments:
![qa_oe_avlsi_i33](https://cloud.githubusercontent.com/assets/13479177/26666155/19bdc180-46bc-11e7-925d-82fbdf638b5e.png)

**Comment by sravanthimodepu** [comment]
Aligned the procedure steps properly.
Yes.. the content in the 11th & 12th experiments are found same from the vlab.co.in page.

**Comment by BSravanthi** [comment]
Closed #34
