### ISSUE TITLE
QA_Design and characterization of basic current mirror_Procedure_improper-alignment

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/analog-cmos-vlsi-circuit-design-iiith#37]
Defect Description :
In the Procedure page of "Design and characterization of basic current mirror" experiment of this lab, the alignment for the second point is improper.

Actual Result :
In the Procedure page of "Design and characterization of basic current mirror" experiment of this lab, the alignment for the second point is improper.

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers:Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

Attachments:
![qa_oe_avlsi_i34](https://cloud.githubusercontent.com/assets/13479177/26666310/de1029c4-46bc-11e7-9fea-36c3a97ec138.png)

**Comment by sravanthimodepu** [comment]
Aligned the procedure steps properly. Hence the issue is fixed.

**Comment by BSravanthi** [comment]
Closed #37
