### ISSUE TITLE
QA_Design and characterization of cascode current mirror_Introduction and Theory_spelling-mistakes

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/analog-cmos-vlsi-circuit-design-iiith#38]
Defect Description :
In the title of the sub-section of Introduction and theory, the Introduction name is mis spelled. 

Actual Result :
In the title of the sub-section of Introduction and theory, the Introduction name is mis spelled. 

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers:Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

Attachments:
![qa_oe_avlsi_i35](https://cloud.githubusercontent.com/assets/13479177/26666732/24284ffc-46bf-11e7-8bef-d268a6a3a91d.png)

**Comment by sravanthimodepu** [comment]
Corrected the spelling mistake of Introduction. Hence resolved the issue.

**Comment by BSravanthi** [comment]
Still the mistake existed. Hence the issue is opened.

**Comment by sravanthimodepu** [comment]
Corrected the spelling mistake.. Hence the issue is fixed.

**Comment by BSravanthi** [comment]
Still the mistake existed. Hence the issue is opened.

**Comment by BSravanthi** [comment]
Closed #38
