### ISSUE TITLE
QA_Design and characterization of cascode current mirror_Procedure_improper-alignment

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/analog-cmos-vlsi-circuit-design-iiith#40]
Defect Description :
In the Procedure page of "Design and characterization of cascode current mirror" experiment of this lab, the alignment for the second point is improper.

Actual Result :
In the Procedure page of "Design and characterization of cascode current mirror" experiment of this lab, the alignment for the second point is improper.

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers:Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

Attachments:
![qa_oe_avlsi_i37](https://cloud.githubusercontent.com/assets/13479177/26666870/e618ab70-46bf-11e7-9778-034dc887057b.png)

**Comment by sravanthimodepu** [comment]
Aligned the procedure steps properly. Hence resolved the issue.

**Comment by BSravanthi** [comment]
Closed #40
