### ISSUE TITLE
QA_Design and characterization of voltage mode buffer : Transfer Characteristics (Vin v/s Vout)_experiment-not-ported

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/analog-cmos-vlsi-circuit-design-iiith#42]
Defect Description :
The experiment section of "Design and characterization of voltage mode buffer : Transfer Characteristics (Vin v/s Vout)" experiment is not ported.

Actual Result :
The experiment section of "Design and characterization of voltage mode buffer : Transfer Characteristics (Vin v/s Vout)" experiment is not ported.

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers:Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

Attachments:
![qa_oe_avlsi_i40](https://cloud.githubusercontent.com/assets/13479177/26667053/da41373a-46c0-11e7-8c8d-ef1b2b6d32c0.png)

**Comment by sravanthimodepu** [comment]
Ported the experiment. Hence resolved the issue.

**Comment by BSravanthi** [comment]
Closed #42
