### ISSUE TITLE
QA_Design and characterization of common source amplifier with Resistive load : Frequency Response (Vin v/s Frequency)_Procedure_improper-alignment

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/analog-cmos-vlsi-circuit-design-iiith#6]
Defect Description :
In the Procedure page of "Design and characterization of common source amplifier with Resistive load : Frequency Response (Vin v/s Frequency)" experiment of this lab, the alignment for the second point is improper.

Actual Result :
In the Procedure page of "Design and characterization of common source amplifier with Resistive load : Frequency Response (Vin v/s Frequency)" experiment of this lab, the alignment for the second point is improper.

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers:Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

Attachments:
![qa_oe_avlsi_i06](https://cloud.githubusercontent.com/assets/13479177/26626192/1a84d8fe-4614-11e7-9f23-dc54234b8346.png)

**Comment by sravanthimodepu** [comment]
Aligned the steps in the order. Hence the issue is fixed.

**Comment by BSravanthi** [comment]
Closed #6
