### ISSUE TITLE
QA_Design and characterization of common source amplifier with Diode connected load : Transfer Characteristics (Vin v/s Vout)_Introduction and Theory_spelling-mistakes

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/analog-cmos-vlsi-circuit-design-iiith#7]
Defect Description :
In the Introduction and Theory page of "Design and characterization of common source amplifier with Diode connected load : Transfer Characteristics (Vin v/s Vout)" experiment of this lab, found spelling mistakes in bread crump and menu items.

Actual Result :
In the Introduction and Theory page of "Design and characterization of common source amplifier with Diode connected load : Transfer Characteristics (Vin v/s Vout)" experiment of this lab, found spelling mistakes in bread crump and menu items.

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers:Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

Attachments:
![qa_oe_avlsi_i07](https://cloud.githubusercontent.com/assets/13479177/26628805/21bdb542-461d-11e7-94d9-30cab080b1f0.png)

**Comment by sravanthimodepu** [comment]
Corrected the spelling mistakes in the page. Hence the issue is fixed.

**Comment by BSravanthi** [comment]
Not yet fixed. Hence the issue is still opened.

**Comment by sravanthimodepu** [comment]
Fixed the issue.

**Comment by BSravanthi** [comment]
While retesting found **introduction** spelling is given as **Introductoin**. Hence re opened

**Comment by sravanthimodepu** [comment]
Corrected the "Introduction" spelling mistake.

**Comment by BSravanthi** [comment]
Closed #7
